// <auto-generated />
using System;
using Budget.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budget.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181006041733_PurchaseDocument")]
    partial class PurchaseDocument
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budget.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("BuyerID");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Budget.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryTypeID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryID");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Budget.Models.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("CategoryTypeID");

                    b.HasIndex("CategoryID");

                    b.ToTable("CategoryTypes");
                });

            modelBuilder.Entity("Budget.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("PurchaseID");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Budget.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price");

                    b.Property<int>("ProductID");

                    b.Property<int>("PurchaseDocumentID");

                    b.Property<float>("Quantity");

                    b.Property<int>("Sum");

                    b.HasKey("PurchaseID");

                    b.HasIndex("PurchaseDocumentID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Budget.Models.PurchaseDocument", b =>
                {
                    b.Property<int>("PurchaseDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerID");

                    b.Property<DateTime>("PurchaseDT");

                    b.Property<int>("SellerID");

                    b.Property<decimal>("TotalCost");

                    b.HasKey("PurchaseDocumentID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("SellerID");

                    b.ToTable("PurchaseDocuments");
                });

            modelBuilder.Entity("Budget.Models.Seller", b =>
                {
                    b.Property<int>("SellerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("RetailPlaceAddress");

                    b.Property<int>("UserInn");

                    b.HasKey("SellerID");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Budget.Models.CategoryType", b =>
                {
                    b.HasOne("Budget.Models.Category")
                        .WithMany("CategoryTypes")
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("Budget.Models.Product", b =>
                {
                    b.HasOne("Budget.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.Models.Purchase")
                        .WithMany("Products")
                        .HasForeignKey("PurchaseID");
                });

            modelBuilder.Entity("Budget.Models.Purchase", b =>
                {
                    b.HasOne("Budget.Models.PurchaseDocument", "PurchaseDocument")
                        .WithMany("Purchases")
                        .HasForeignKey("PurchaseDocumentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.Models.PurchaseDocument", b =>
                {
                    b.HasOne("Budget.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.Models.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
